platform :ios, "6.0"

target "Twatch" do

pod 'AFNetworking'

pod 'SDWebImage'

pod 'MBProgressHUD', '~> 0.8'

pod 'ZipArchive', '~> 1.2.0'

pod 'SBJson', '~> 3.2'

pod 'GDataXML-HTML', '~> 1.1.0'

end

